### ISSUE TITLE
Drupal.org distribution?

### ISSUE THREAD

**Issue by matt-bernhardt** [berkmancenter/amber_drupal#13]
Is there a plan to distribute this module via the usual channels at Drupal.org? I see a sandbox project there: https://www.drupal.org/sandbox/jlicht/2633514 which looks like it might be heading in that direction, but it isn't clear yet.

Basically, I'm wondering what the best way to stay current with this project will be - whether I need to just watch GitHub here, or if the work will be switched to Drupal.org at some point.

**Comment by jlicht** [comment]
We are working on getting this through the process at Drupal.org - once it's promoted to a full project that will be the best place to follow it.

**Comment by zealfire** [comment]
Hello everyone.
Any progress on making this available to d.o. ?
Also since Drupal 8 is already out, so are there any plans to port this to D8?
If this has not already started then tell if I can be of any help ?
Thanks.

**Comment by jlicht** [comment]
The module is now available on Drupal.org: https://www.drupal.org/project/amber

Please check it out, and feel free to log any questions or issues there.
